### ISSUE TITLE
What gets returned for ?content=nonconfig

### ISSUE THREAD

**Issue by mrdeep1** [boucadair/draft-ietf-dots-data-channel#4]
````
GET /restconf/data/ietf-dots-data-channel:dots-data/dots-client=sGI0F_6BMVsoz91ssmLpVw/aliases?content=nonconfig
````

Which of the following 2 responses is valid?
[name is a configuration item]

````
{"ietf-dots-data-channel:aliases":{"alias":[{"pending-lifetime":10043},{"pending-lifetime":10043},{"pending-lifetime":10043},{"pending-lifetime":10043},{"pending-lifetime":10043}]}}
````

or

````
{"ietf-dots-data-channel:aliases":{"alias":[{"name":"C1-target_ip-01","pending-lifetime":10043},{"name":"test-target-ip1","pending-lifetime"10043},{"name":"test1","pending-lifetime":10043},{"name":"test2","pending-lifetime":10043},{"name":"test4","pending-lifetime":10043}]}}
````

**Comment by mrdeep1** [comment]
The same question is true for ACLs

**Comment by eurekaeru** [comment]
one solution is:
treat 'name'
+--rw name                 string
as nonconfig?
+--ro name                 string
because PUT should not change 'name' (only DELETE->POST will work)

**Comment by mrdeep1** [comment]
Unfortunately, the name has to always be in the body for a POST / PUT, so it has to be rw

**Comment by mrdeep1** [comment]
````
https://tools.ietf.org/html/draft-ietf-netmod-yang-13

4.2.3.  State Data

   YANG can model state data, as well as configuration data, based on
   the "config" statement.  When a node is tagged with "config false",
   its subhierarchy is flagged as state data, to be reported using
   NETCONF's <get> operation, not the <get-config> operation.  Parent
   containers, lists, and key leafs are reported also, giving the
   context for the state data.
````

The key leaf (in our case 'name') is to be reported to give the context of the state data

**Comment by boucadair** [comment]
Hi,

In reference to “Example 3: content=nonconfig” of RFC8040, the correct answer IMHO is the second one.

Cheers,
Med

De : mrdeep1 [mailto:notifications@github.com]
Envoyé : samedi 14 juillet 2018 16:13
À : boucadair/draft-ietf-dots-data-channel
Cc : Subscribed
Objet : [boucadair/draft-ietf-dots-data-channel] What gets returned for ?content=nonconfig (#4)


GET /restconf/data/ietf-dots-data-channel:dots-data/dots-client=sGI0F_6BMVsoz91ssmLpVw/aliases?content=nonconfig

Which of the following 2 responses is valid?
[name is a configuration item]

{"ietf-dots-data-channel:aliases":{"alias":[{"pending-lifetime":10043},{"pending-lifetime":10043},{"pending-lifetime":10043},{"pending-lifetime":10043},{"pending-lifetime":10043}]}}

or

{"ietf-dots-data-channel:aliases":{"alias":[{"name":"C1-target_ip-01","pending-lifetime":10043},{"name":"test-target-ip1","pending-lifetime"10043},{"name":"test1","pending-lifetime":10043},{"name":"test2","pending-lifetime":10043},{"name":"test4","pending-lifetime":10043}]}}

**Comment by mrdeep1** [comment]
Agreed as it is a key leaf ("name")

**Comment by eurekaeru** [comment]
Yes that's correct
